#################
# Demo Commands #
#################

bin := "./target/release/standard_vault"

status:
    RUST_LOG=info {{ bin }} status

deposit:
    RUST_LOG=info {{ bin }} deposit

repay:
    RUST_LOG=info {{ bin }} repay $({{ bcli }} -rpcwallet=miner getnewaddress)

liquidate:
    RUST_LOG=info {{ bin }} liquidate

timeout:
    RUST_LOG=info {{ bin }} timeout $({{ bcli }} -rpcwallet=miner getnewaddress)


###################################
# Build and bootstrapping commands #
###################################

bitcoin_datadir := "./bitcoin-data"
bcli := "./bitcoin-core-cat/src/bitcoin-cli -regtest -rpcuser=user -rpcpassword=password"

start-bitcoind *ARGS:
    mkdir -p {{ bitcoin_datadir }}
    ./bitcoin-core-cat/src/bitcoind -regtest -timeout=15000 -server=1 -txindex=1 -rpcuser=user -rpcpassword=password -datadir={{bitcoin_datadir}} {{ ARGS }}

stop-bitcoind:
    {{ bcli }} stop

clean-bitcoin-data:
    rm -rf {{ bitcoin_datadir }}

build:
    cargo build --release

bootstrap:
    bash ./scripts/build_bitcoincore.sh
    just build
    just clean-bitcoin-data
    just start-bitcoind


